#!/usr/bin/env bash

# CryoSPARC web installer script
# Copyright 2016 Structura Biotechnology Inc.

# abort if any commands fail
set -e

# check if git is installed
git_path=$(which git) || true
if [[ -x "$git_path" ]] ; then
    echo " Found git at $git_path"
else
    echo "! Error: git not found." 
    echo "  Please install git. Use "
    echo "    sudo apt-get install git"
    echo "  on Ubuntu/Debian."
    exit 1
fi

# check if ssh keys are set up with github
if ssh -T git@github.com 2>&1 | grep -q "successfully"; then
    echo "  Git keys are correctly setup for github.com."
else
    echo "! Error: git keys are not set up for github.com."
    echo "  Please add your ssh RSA public key to github.com."
    if [[ -e "$HOME/.ssh/id_rsa.pub" ]] ; then
        echo "  Found an SSH key at ~/.ssh/id_rsa.pub"
        echo "  Copy the following key and add it to github.com, then run this script again:"
        echo "--------------------------------------------------------------"
        cat $HOME/.ssh/id_rsa.pub
        echo "--------------------------------------------------------------"
    else
        echo "  A public key was not found in the standard location."
        read -p "  Create a new ssh key? y | n (abort): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]] ; then
            ssh-keygen -t rsa -N "" -f $HOME/.ssh/id_rsa
            echo "  Created new key."
            echo "  Copy the following key and add it to github.com, then run this script again:"
            echo "--------------------------------------------------------------"
            cat $HOME/.ssh/id_rsa.pub
            echo "--------------------------------------------------------------"
            exit 1
        else
            exit 1
        fi
    fi
    exit 1
fi

# clone cryosparc-deploy
git clone git@github.com:cryoem-uoft/cryosparc-deploy.git cryosparc
# run install.sh with default options
cd cryosparc
./install.sh 

